### ISSUE TITLE
Accessing /tournaments crashes the server

### ISSUE THREAD

**Issue by twizmwazin** [SunshineAPI/WebAPI#47]
```
tls.js:182
      var commonNames = cert.subject.CN;
                                    ^

TypeError: Cannot read property 'CN' of undefined
    at Object.checkServerIdentity (tls.js:182:37)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:29)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:566:8)
```

**Comment by gilrosenthal** [comment]
Hmm, cant seem to replicate this. @twizmwazin  can you tell me the exact steps?

**Comment by twizmwazin** [comment]
I actually tried replicating it and couldn't either. I'll look in to it, it may be a small chance or something. It may have also been a connection issue.
