### ISSUE TITLE
Accessing /players/player_name crashes application

### ISSUE THREAD

**Issue by doriand01** [SunshineAPI/WebAPI#51]
```
dorian@dorian-VGN-FZ140E:~/WebAPI$ nodejs bin/www
Connecting to redis...
Express server listening at 0.0.0.0:3000
Established redis connection.

TypeError: Cannot call method 'replace' of null
    at /home/dorian/WebAPI/modules/parser.js:69:67
    at Request._callback (/home/dorian/WebAPI/modules/helpers.js:21:3)
    at Request.self.callback (/home/dorian/WebAPI/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/dorian/WebAPI/node_modules/request/request.js:1057:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/dorian/WebAPI/node_modules/request/request.js:1003:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

NOTE: putting 'localhost' in the address bar will successfully take you to the homepage.

**Comment by jengel3** [comment]
#50
